export interface Location {
  slug: string;
  name: string;
  country: string;
  countryCode: string;
  continent: "North America" | "Europe" | "Asia" | "Oceania" | "South America" | "Africa" | "Middle East";
  region?: string;
  currency: string;
  currencySymbol: string;
  nearby: string[];
  eventCost: string;
  mealPrepCost: string;
  fullTimeCost: string;
}

export const LOCATIONS: Location[] = [
  // ── UNITED STATES ───────────────────────────────────────────────
  { slug: "new-york", name: "New York", country: "United States", countryCode: "US", continent: "North America", region: "NY", currency: "USD", currencySymbol: "$", nearby: ["brooklyn", "long-island", "hamptons", "new-jersey", "connecticut", "hudson-valley"], eventCost: "$400–$1,200", mealPrepCost: "$250–$500/day", fullTimeCost: "$70,000–$130,000/yr" },
  { slug: "brooklyn", name: "Brooklyn", country: "United States", countryCode: "US", continent: "North America", region: "NY", currency: "USD", currencySymbol: "$", nearby: ["new-york", "long-island", "new-jersey"], eventCost: "$350–$1,000", mealPrepCost: "$200–$450/day", fullTimeCost: "$65,000–$120,000/yr" },
  { slug: "long-island", name: "Long Island", country: "United States", countryCode: "US", continent: "North America", region: "NY", currency: "USD", currencySymbol: "$", nearby: ["new-york", "brooklyn", "hamptons"], eventCost: "$350–$900", mealPrepCost: "$200–$400/day", fullTimeCost: "$60,000–$110,000/yr" },
  { slug: "hamptons", name: "The Hamptons", country: "United States", countryCode: "US", continent: "North America", region: "NY", currency: "USD", currencySymbol: "$", nearby: ["new-york", "long-island", "brooklyn"], eventCost: "$600–$2,000", mealPrepCost: "$400–$800/day", fullTimeCost: "$90,000–$160,000/yr" },
  { slug: "hudson-valley", name: "Hudson Valley", country: "United States", countryCode: "US", continent: "North America", region: "NY", currency: "USD", currencySymbol: "$", nearby: ["new-york", "connecticut", "rochester"], eventCost: "$300–$800", mealPrepCost: "$180–$350/day", fullTimeCost: "$55,000–$100,000/yr" },
  { slug: "rochester", name: "Rochester", country: "United States", countryCode: "US", continent: "North America", region: "NY", currency: "USD", currencySymbol: "$", nearby: ["buffalo", "hudson-valley", "new-york"], eventCost: "$250–$700", mealPrepCost: "$150–$300/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "buffalo", name: "Buffalo", country: "United States", countryCode: "US", continent: "North America", region: "NY", currency: "USD", currencySymbol: "$", nearby: ["rochester", "new-york"], eventCost: "$250–$650", mealPrepCost: "$140–$280/day", fullTimeCost: "$42,000–$80,000/yr" },
  { slug: "los-angeles", name: "Los Angeles", country: "United States", countryCode: "US", continent: "North America", region: "CA", currency: "USD", currencySymbol: "$", nearby: ["orange-county", "san-diego", "palm-springs", "santa-barbara", "malibu"], eventCost: "$500–$1,500", mealPrepCost: "$300–$600/day", fullTimeCost: "$75,000–$140,000/yr" },
  { slug: "san-francisco", name: "San Francisco", country: "United States", countryCode: "US", continent: "North America", region: "CA", currency: "USD", currencySymbol: "$", nearby: ["bay-area", "oakland", "napa", "sonoma", "san-jose"], eventCost: "$500–$1,400", mealPrepCost: "$300–$600/day", fullTimeCost: "$80,000–$150,000/yr" },
  { slug: "bay-area", name: "Bay Area", country: "United States", countryCode: "US", continent: "North America", region: "CA", currency: "USD", currencySymbol: "$", nearby: ["san-francisco", "oakland", "napa", "san-jose"], eventCost: "$450–$1,300", mealPrepCost: "$280–$550/day", fullTimeCost: "$75,000–$140,000/yr" },
  { slug: "oakland", name: "Oakland", country: "United States", countryCode: "US", continent: "North America", region: "CA", currency: "USD", currencySymbol: "$", nearby: ["san-francisco", "bay-area", "napa"], eventCost: "$380–$1,000", mealPrepCost: "$220–$450/day", fullTimeCost: "$65,000–$120,000/yr" },
  { slug: "san-diego", name: "San Diego", country: "United States", countryCode: "US", continent: "North America", region: "CA", currency: "USD", currencySymbol: "$", nearby: ["los-angeles", "orange-county", "temecula", "palm-springs"], eventCost: "$400–$1,100", mealPrepCost: "$250–$500/day", fullTimeCost: "$65,000–$120,000/yr" },
  { slug: "orange-county", name: "Orange County", country: "United States", countryCode: "US", continent: "North America", region: "CA", currency: "USD", currencySymbol: "$", nearby: ["los-angeles", "san-diego", "palm-springs"], eventCost: "$400–$1,100", mealPrepCost: "$250–$490/day", fullTimeCost: "$65,000–$120,000/yr" },
  { slug: "palm-springs", name: "Palm Springs", country: "United States", countryCode: "US", continent: "North America", region: "CA", currency: "USD", currencySymbol: "$", nearby: ["los-angeles", "san-diego", "orange-county", "joshua-tree"], eventCost: "$400–$1,200", mealPrepCost: "$250–$500/day", fullTimeCost: "$60,000–$115,000/yr" },
  { slug: "joshua-tree", name: "Joshua Tree", country: "United States", countryCode: "US", continent: "North America", region: "CA", currency: "USD", currencySymbol: "$", nearby: ["palm-springs", "los-angeles", "san-diego"], eventCost: "$350–$900", mealPrepCost: "$200–$400/day", fullTimeCost: "$50,000–$95,000/yr" },
  { slug: "napa", name: "Napa", country: "United States", countryCode: "US", continent: "North America", region: "CA", currency: "USD", currencySymbol: "$", nearby: ["san-francisco", "bay-area", "sonoma", "paso-robles"], eventCost: "$450–$1,400", mealPrepCost: "$280–$550/day", fullTimeCost: "$70,000–$130,000/yr" },
  { slug: "sonoma", name: "Sonoma", country: "United States", countryCode: "US", continent: "North America", region: "CA", currency: "USD", currencySymbol: "$", nearby: ["napa", "san-francisco", "bay-area"], eventCost: "$400–$1,200", mealPrepCost: "$250–$500/day", fullTimeCost: "$65,000–$120,000/yr" },
  { slug: "paso-robles", name: "Paso Robles", country: "United States", countryCode: "US", continent: "North America", region: "CA", currency: "USD", currencySymbol: "$", nearby: ["napa", "santa-barbara", "san-francisco"], eventCost: "$350–$1,000", mealPrepCost: "$200–$420/day", fullTimeCost: "$55,000–$100,000/yr" },
  { slug: "temecula", name: "Temecula", country: "United States", countryCode: "US", continent: "North America", region: "CA", currency: "USD", currencySymbol: "$", nearby: ["san-diego", "los-angeles", "orange-county"], eventCost: "$350–$950", mealPrepCost: "$200–$400/day", fullTimeCost: "$55,000–$100,000/yr" },
  { slug: "miami", name: "Miami", country: "United States", countryCode: "US", continent: "North America", region: "FL", currency: "USD", currencySymbol: "$", nearby: ["fort-lauderdale", "west-palm-beach", "florida-keys", "naples"], eventCost: "$450–$1,400", mealPrepCost: "$280–$550/day", fullTimeCost: "$65,000–$125,000/yr" },
  { slug: "fort-lauderdale", name: "Fort Lauderdale", country: "United States", countryCode: "US", continent: "North America", region: "FL", currency: "USD", currencySymbol: "$", nearby: ["miami", "west-palm-beach", "boca-raton"], eventCost: "$380–$1,100", mealPrepCost: "$220–$450/day", fullTimeCost: "$58,000–$110,000/yr" },
  { slug: "west-palm-beach", name: "West Palm Beach", country: "United States", countryCode: "US", continent: "North America", region: "FL", currency: "USD", currencySymbol: "$", nearby: ["miami", "fort-lauderdale", "vero-beach"], eventCost: "$380–$1,100", mealPrepCost: "$220–$450/day", fullTimeCost: "$58,000–$110,000/yr" },
  { slug: "vero-beach", name: "Vero Beach", country: "United States", countryCode: "US", continent: "North America", region: "FL", currency: "USD", currencySymbol: "$", nearby: ["west-palm-beach", "fort-lauderdale", "orlando"], eventCost: "$320–$900", mealPrepCost: "$180–$380/day", fullTimeCost: "$50,000–$95,000/yr" },
  { slug: "naples-fl", name: "Naples", country: "United States", countryCode: "US", continent: "North America", region: "FL", currency: "USD", currencySymbol: "$", nearby: ["miami", "fort-lauderdale", "sarasota"], eventCost: "$380–$1,100", mealPrepCost: "$220–$450/day", fullTimeCost: "$58,000–$110,000/yr" },
  { slug: "orlando", name: "Orlando", country: "United States", countryCode: "US", continent: "North America", region: "FL", currency: "USD", currencySymbol: "$", nearby: ["kissimmee", "tampa", "daytona-beach", "vero-beach"], eventCost: "$320–$900", mealPrepCost: "$180–$380/day", fullTimeCost: "$50,000–$95,000/yr" },
  { slug: "kissimmee", name: "Kissimmee", country: "United States", countryCode: "US", continent: "North America", region: "FL", currency: "USD", currencySymbol: "$", nearby: ["orlando", "tampa", "daytona-beach"], eventCost: "$280–$800", mealPrepCost: "$160–$340/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "tampa", name: "Tampa", country: "United States", countryCode: "US", continent: "North America", region: "FL", currency: "USD", currencySymbol: "$", nearby: ["orlando", "sarasota", "clearwater", "st-pete"], eventCost: "$320–$900", mealPrepCost: "$180–$370/day", fullTimeCost: "$50,000–$95,000/yr" },
  { slug: "destin", name: "Destin", country: "United States", countryCode: "US", continent: "North America", region: "FL", currency: "USD", currencySymbol: "$", nearby: ["30a", "gulf-shores", "pensacola", "panama-city"], eventCost: "$350–$1,000", mealPrepCost: "$200–$420/day", fullTimeCost: "$52,000–$100,000/yr" },
  { slug: "30a", name: "30A", country: "United States", countryCode: "US", continent: "North America", region: "FL", currency: "USD", currencySymbol: "$", nearby: ["destin", "rosemary-beach", "gulf-shores", "panama-city"], eventCost: "$350–$1,100", mealPrepCost: "$200–$450/day", fullTimeCost: "$55,000–$105,000/yr" },
  { slug: "rosemary-beach", name: "Rosemary Beach", country: "United States", countryCode: "US", continent: "North America", region: "FL", currency: "USD", currencySymbol: "$", nearby: ["30a", "destin", "gulf-shores"], eventCost: "$380–$1,100", mealPrepCost: "$220–$460/day", fullTimeCost: "$58,000–$108,000/yr" },
  { slug: "key-west", name: "Key West", country: "United States", countryCode: "US", continent: "North America", region: "FL", currency: "USD", currencySymbol: "$", nearby: ["miami", "naples-fl", "fort-lauderdale"], eventCost: "$400–$1,200", mealPrepCost: "$240–$480/day", fullTimeCost: "$60,000–$115,000/yr" },
  { slug: "jacksonville", name: "Jacksonville", country: "United States", countryCode: "US", continent: "North America", region: "FL", currency: "USD", currencySymbol: "$", nearby: ["savannah", "orlando", "st-augustine"], eventCost: "$280–$800", mealPrepCost: "$160–$340/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "gulf-shores", name: "Gulf Shores", country: "United States", countryCode: "US", continent: "North America", region: "AL", currency: "USD", currencySymbol: "$", nearby: ["30a", "destin", "orange-beach", "biloxi"], eventCost: "$320–$900", mealPrepCost: "$180–$370/day", fullTimeCost: "$48,000–$92,000/yr" },
  { slug: "atlanta", name: "Atlanta", country: "United States", countryCode: "US", continent: "North America", region: "GA", currency: "USD", currencySymbol: "$", nearby: ["savannah", "charlotte", "nashville", "greenville-sc"], eventCost: "$350–$1,000", mealPrepCost: "$200–$420/day", fullTimeCost: "$55,000–$105,000/yr" },
  { slug: "savannah", name: "Savannah", country: "United States", countryCode: "US", continent: "North America", region: "GA", currency: "USD", currencySymbol: "$", nearby: ["atlanta", "charleston", "jacksonville", "hilton-head"], eventCost: "$300–$850", mealPrepCost: "$170–$360/day", fullTimeCost: "$48,000–$92,000/yr" },
  { slug: "charleston", name: "Charleston", country: "United States", countryCode: "US", continent: "North America", region: "SC", currency: "USD", currencySymbol: "$", nearby: ["savannah", "hilton-head", "myrtle-beach", "charlotte"], eventCost: "$350–$1,000", mealPrepCost: "$200–$420/day", fullTimeCost: "$55,000–$102,000/yr" },
  { slug: "hilton-head", name: "Hilton Head", country: "United States", countryCode: "US", continent: "North America", region: "SC", currency: "USD", currencySymbol: "$", nearby: ["charleston", "savannah", "kiawah-island"], eventCost: "$350–$1,100", mealPrepCost: "$200–$440/day", fullTimeCost: "$55,000–$105,000/yr" },
  { slug: "kiawah-island", name: "Kiawah Island", country: "United States", countryCode: "US", continent: "North America", region: "SC", currency: "USD", currencySymbol: "$", nearby: ["charleston", "hilton-head", "savannah"], eventCost: "$400–$1,200", mealPrepCost: "$240–$480/day", fullTimeCost: "$60,000–$115,000/yr" },
  { slug: "isle-of-palms", name: "Isle of Palms", country: "United States", countryCode: "US", continent: "North America", region: "SC", currency: "USD", currencySymbol: "$", nearby: ["charleston", "hilton-head", "kiawah-island"], eventCost: "$380–$1,100", mealPrepCost: "$220–$450/day", fullTimeCost: "$58,000–$110,000/yr" },
  { slug: "myrtle-beach", name: "Myrtle Beach", country: "United States", countryCode: "US", continent: "North America", region: "SC", currency: "USD", currencySymbol: "$", nearby: ["charleston", "wilmington-nc", "outer-banks"], eventCost: "$300–$850", mealPrepCost: "$170–$360/day", fullTimeCost: "$48,000–$90,000/yr" },
  { slug: "greenville-sc", name: "Greenville", country: "United States", countryCode: "US", continent: "North America", region: "SC", currency: "USD", currencySymbol: "$", nearby: ["charlotte", "atlanta", "asheville"], eventCost: "$280–$800", mealPrepCost: "$160–$330/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "charlotte", name: "Charlotte", country: "United States", countryCode: "US", continent: "North America", region: "NC", currency: "USD", currencySymbol: "$", nearby: ["raleigh", "greenville-sc", "asheville", "winston-salem"], eventCost: "$320–$900", mealPrepCost: "$180–$380/day", fullTimeCost: "$52,000–$98,000/yr" },
  { slug: "raleigh", name: "Raleigh", country: "United States", countryCode: "US", continent: "North America", region: "NC", currency: "USD", currencySymbol: "$", nearby: ["charlotte", "greensboro", "outer-banks", "wilmington-nc"], eventCost: "$300–$850", mealPrepCost: "$170–$360/day", fullTimeCost: "$50,000–$95,000/yr" },
  { slug: "asheville", name: "Asheville", country: "United States", countryCode: "US", continent: "North America", region: "NC", currency: "USD", currencySymbol: "$", nearby: ["charlotte", "greenville-sc", "knoxville"], eventCost: "$320–$950", mealPrepCost: "$180–$380/day", fullTimeCost: "$50,000–$95,000/yr" },
  { slug: "wilmington-nc", name: "Wilmington", country: "United States", countryCode: "US", continent: "North America", region: "NC", currency: "USD", currencySymbol: "$", nearby: ["outer-banks", "myrtle-beach", "raleigh"], eventCost: "$280–$800", mealPrepCost: "$160–$330/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "greensboro", name: "Greensboro", country: "United States", countryCode: "US", continent: "North America", region: "NC", currency: "USD", currencySymbol: "$", nearby: ["charlotte", "raleigh", "winston-salem"], eventCost: "$270–$750", mealPrepCost: "$150–$320/day", fullTimeCost: "$44,000–$82,000/yr" },
  { slug: "winston-salem", name: "Winston-Salem", country: "United States", countryCode: "US", continent: "North America", region: "NC", currency: "USD", currencySymbol: "$", nearby: ["greensboro", "charlotte", "raleigh"], eventCost: "$270–$750", mealPrepCost: "$150–$310/day", fullTimeCost: "$43,000–$80,000/yr" },
  { slug: "outer-banks", name: "Outer Banks", country: "United States", countryCode: "US", continent: "North America", region: "NC", currency: "USD", currencySymbol: "$", nearby: ["wilmington-nc", "virginia-beach", "raleigh"], eventCost: "$350–$1,000", mealPrepCost: "$200–$420/day", fullTimeCost: "$52,000–$100,000/yr" },
  { slug: "nashville", name: "Nashville", country: "United States", countryCode: "US", continent: "North America", region: "TN", currency: "USD", currencySymbol: "$", nearby: ["knoxville", "memphis", "louisville", "atlanta"], eventCost: "$350–$1,000", mealPrepCost: "$200–$420/day", fullTimeCost: "$55,000–$102,000/yr" },
  { slug: "knoxville", name: "Knoxville", country: "United States", countryCode: "US", continent: "North America", region: "TN", currency: "USD", currencySymbol: "$", nearby: ["nashville", "asheville", "chattanooga"], eventCost: "$270–$750", mealPrepCost: "$150–$310/day", fullTimeCost: "$43,000–$80,000/yr" },
  { slug: "gatlinburg", name: "Gatlinburg", country: "United States", countryCode: "US", continent: "North America", region: "TN", currency: "USD", currencySymbol: "$", nearby: ["knoxville", "asheville", "nashville"], eventCost: "$300–$850", mealPrepCost: "$170–$360/day", fullTimeCost: "$48,000–$90,000/yr" },
  { slug: "chicago", name: "Chicago", country: "United States", countryCode: "US", continent: "North America", region: "IL", currency: "USD", currencySymbol: "$", nearby: ["milwaukee", "indianapolis", "st-louis", "detroit"], eventCost: "$400–$1,200", mealPrepCost: "$250–$500/day", fullTimeCost: "$65,000–$120,000/yr" },
  { slug: "houston", name: "Houston", country: "United States", countryCode: "US", continent: "North America", region: "TX", currency: "USD", currencySymbol: "$", nearby: ["dallas", "austin", "san-antonio", "galveston"], eventCost: "$350–$1,000", mealPrepCost: "$200–$420/day", fullTimeCost: "$55,000–$105,000/yr" },
  { slug: "dallas", name: "Dallas", country: "United States", countryCode: "US", continent: "North America", region: "TX", currency: "USD", currencySymbol: "$", nearby: ["fort-worth", "houston", "austin", "san-antonio"], eventCost: "$350–$1,000", mealPrepCost: "$200–$420/day", fullTimeCost: "$55,000–$105,000/yr" },
  { slug: "fort-worth", name: "Fort Worth", country: "United States", countryCode: "US", continent: "North America", region: "TX", currency: "USD", currencySymbol: "$", nearby: ["dallas", "houston", "austin"], eventCost: "$320–$900", mealPrepCost: "$180–$380/day", fullTimeCost: "$50,000–$95,000/yr" },
  { slug: "austin", name: "Austin", country: "United States", countryCode: "US", continent: "North America", region: "TX", currency: "USD", currencySymbol: "$", nearby: ["dallas", "houston", "san-antonio", "fredericksburg"], eventCost: "$380–$1,100", mealPrepCost: "$220–$460/day", fullTimeCost: "$60,000–$115,000/yr" },
  { slug: "san-antonio", name: "San Antonio", country: "United States", countryCode: "US", continent: "North America", region: "TX", currency: "USD", currencySymbol: "$", nearby: ["austin", "houston", "dallas", "fredericksburg"], eventCost: "$300–$850", mealPrepCost: "$170–$360/day", fullTimeCost: "$48,000–$92,000/yr" },
  { slug: "fredericksburg", name: "Fredericksburg", country: "United States", countryCode: "US", continent: "North America", region: "TX", currency: "USD", currencySymbol: "$", nearby: ["austin", "san-antonio", "dallas"], eventCost: "$320–$950", mealPrepCost: "$180–$380/day", fullTimeCost: "$50,000–$95,000/yr" },
  { slug: "galveston", name: "Galveston", country: "United States", countryCode: "US", continent: "North America", region: "TX", currency: "USD", currencySymbol: "$", nearby: ["houston", "dallas", "austin"], eventCost: "$300–$850", mealPrepCost: "$170–$360/day", fullTimeCost: "$48,000–$90,000/yr" },
  { slug: "el-paso", name: "El Paso", country: "United States", countryCode: "US", continent: "North America", region: "TX", currency: "USD", currencySymbol: "$", nearby: ["san-antonio", "albuquerque", "tucson"], eventCost: "$250–$700", mealPrepCost: "$140–$290/day", fullTimeCost: "$40,000–$78,000/yr" },
  { slug: "denver", name: "Denver", country: "United States", countryCode: "US", continent: "North America", region: "CO", currency: "USD", currencySymbol: "$", nearby: ["breckenridge", "vail", "boulder", "colorado-springs"], eventCost: "$380–$1,100", mealPrepCost: "$220–$460/day", fullTimeCost: "$60,000–$115,000/yr" },
  { slug: "breckenridge", name: "Breckenridge", country: "United States", countryCode: "US", continent: "North America", region: "CO", currency: "USD", currencySymbol: "$", nearby: ["denver", "vail", "aspen"], eventCost: "$450–$1,400", mealPrepCost: "$280–$560/day", fullTimeCost: "$65,000–$125,000/yr" },
  { slug: "vail", name: "Vail", country: "United States", countryCode: "US", continent: "North America", region: "CO", currency: "USD", currencySymbol: "$", nearby: ["denver", "breckenridge", "aspen"], eventCost: "$500–$1,600", mealPrepCost: "$320–$620/day", fullTimeCost: "$70,000–$135,000/yr" },
  { slug: "aspen", name: "Aspen", country: "United States", countryCode: "US", continent: "North America", region: "CO", currency: "USD", currencySymbol: "$", nearby: ["vail", "breckenridge", "denver"], eventCost: "$600–$2,000", mealPrepCost: "$380–$750/day", fullTimeCost: "$85,000–$160,000/yr" },
  { slug: "scottsdale", name: "Scottsdale", country: "United States", countryCode: "US", continent: "North America", region: "AZ", currency: "USD", currencySymbol: "$", nearby: ["phoenix", "sedona", "tucson", "gilbert"], eventCost: "$380–$1,100", mealPrepCost: "$220–$460/day", fullTimeCost: "$58,000–$110,000/yr" },
  { slug: "phoenix", name: "Phoenix", country: "United States", countryCode: "US", continent: "North America", region: "AZ", currency: "USD", currencySymbol: "$", nearby: ["scottsdale", "sedona", "tucson", "gilbert"], eventCost: "$320–$950", mealPrepCost: "$180–$390/day", fullTimeCost: "$52,000–$100,000/yr" },
  { slug: "sedona", name: "Sedona", country: "United States", countryCode: "US", continent: "North America", region: "AZ", currency: "USD", currencySymbol: "$", nearby: ["scottsdale", "phoenix", "flagstaff"], eventCost: "$400–$1,200", mealPrepCost: "$240–$480/day", fullTimeCost: "$58,000–$110,000/yr" },
  { slug: "tucson", name: "Tucson", country: "United States", countryCode: "US", continent: "North America", region: "AZ", currency: "USD", currencySymbol: "$", nearby: ["phoenix", "scottsdale", "el-paso"], eventCost: "$280–$800", mealPrepCost: "$160–$330/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "gilbert", name: "Gilbert", country: "United States", countryCode: "US", continent: "North America", region: "AZ", currency: "USD", currencySymbol: "$", nearby: ["scottsdale", "phoenix", "tucson"], eventCost: "$300–$850", mealPrepCost: "$170–$350/day", fullTimeCost: "$48,000–$90,000/yr" },
  { slug: "las-vegas", name: "Las Vegas", country: "United States", countryCode: "US", continent: "North America", region: "NV", currency: "USD", currencySymbol: "$", nearby: ["los-angeles", "phoenix", "scottsdale"], eventCost: "$450–$1,400", mealPrepCost: "$280–$560/day", fullTimeCost: "$60,000–$120,000/yr" },
  { slug: "seattle", name: "Seattle", country: "United States", countryCode: "US", continent: "North America", region: "WA", currency: "USD", currencySymbol: "$", nearby: ["portland", "olympia", "tacoma"], eventCost: "$420–$1,200", mealPrepCost: "$260–$520/day", fullTimeCost: "$68,000–$128,000/yr" },
  { slug: "portland", name: "Portland", country: "United States", countryCode: "US", continent: "North America", region: "OR", currency: "USD", currencySymbol: "$", nearby: ["seattle", "bend", "eugene"], eventCost: "$350–$1,000", mealPrepCost: "$200–$420/day", fullTimeCost: "$55,000–$105,000/yr" },
  { slug: "bend", name: "Bend", country: "United States", countryCode: "US", continent: "North America", region: "OR", currency: "USD", currencySymbol: "$", nearby: ["portland", "eugene", "seattle"], eventCost: "$320–$950", mealPrepCost: "$180–$380/day", fullTimeCost: "$50,000–$98,000/yr" },
  { slug: "eugene", name: "Eugene", country: "United States", countryCode: "US", continent: "North America", region: "OR", currency: "USD", currencySymbol: "$", nearby: ["portland", "bend"], eventCost: "$280–$800", mealPrepCost: "$160–$330/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "boston", name: "Boston", country: "United States", countryCode: "US", continent: "North America", region: "MA", currency: "USD", currencySymbol: "$", nearby: ["cape-cod", "nantucket", "rhode-island", "new-hampshire", "new-york"], eventCost: "$400–$1,200", mealPrepCost: "$250–$500/day", fullTimeCost: "$65,000–$122,000/yr" },
  { slug: "cape-cod", name: "Cape Cod", country: "United States", countryCode: "US", continent: "North America", region: "MA", currency: "USD", currencySymbol: "$", nearby: ["boston", "nantucket", "rhode-island"], eventCost: "$380–$1,100", mealPrepCost: "$220–$450/day", fullTimeCost: "$58,000–$110,000/yr" },
  { slug: "nantucket", name: "Nantucket", country: "United States", countryCode: "US", continent: "North America", region: "MA", currency: "USD", currencySymbol: "$", nearby: ["cape-cod", "boston", "rhode-island"], eventCost: "$500–$1,800", mealPrepCost: "$320–$650/day", fullTimeCost: "$75,000–$145,000/yr" },
  { slug: "portland-maine", name: "Portland", country: "United States", countryCode: "US", continent: "North America", region: "ME", currency: "USD", currencySymbol: "$", nearby: ["boston", "new-hampshire", "cape-cod"], eventCost: "$300–$900", mealPrepCost: "$170–$370/day", fullTimeCost: "$48,000–$92,000/yr" },
  { slug: "rhode-island", name: "Rhode Island", country: "United States", countryCode: "US", continent: "North America", region: "RI", currency: "USD", currencySymbol: "$", nearby: ["boston", "cape-cod", "new-york", "connecticut"], eventCost: "$320–$950", mealPrepCost: "$180–$380/day", fullTimeCost: "$52,000–$98,000/yr" },
  { slug: "newport-ri", name: "Newport", country: "United States", countryCode: "US", continent: "North America", region: "RI", currency: "USD", currencySymbol: "$", nearby: ["rhode-island", "boston", "cape-cod"], eventCost: "$450–$1,400", mealPrepCost: "$280–$560/day", fullTimeCost: "$65,000–$125,000/yr" },
  { slug: "connecticut", name: "Connecticut", country: "United States", countryCode: "US", continent: "North America", region: "CT", currency: "USD", currencySymbol: "$", nearby: ["new-york", "boston", "rhode-island", "greenwich"], eventCost: "$380–$1,100", mealPrepCost: "$220–$460/day", fullTimeCost: "$60,000–$115,000/yr" },
  { slug: "greenwich", name: "Greenwich", country: "United States", countryCode: "US", continent: "North America", region: "CT", currency: "USD", currencySymbol: "$", nearby: ["new-york", "connecticut", "hamptons"], eventCost: "$500–$1,600", mealPrepCost: "$320–$620/day", fullTimeCost: "$75,000–$145,000/yr" },
  { slug: "new-hampshire", name: "New Hampshire", country: "United States", countryCode: "US", continent: "North America", region: "NH", currency: "USD", currencySymbol: "$", nearby: ["boston", "portland-maine", "vermont"], eventCost: "$300–$850", mealPrepCost: "$170–$360/day", fullTimeCost: "$48,000–$90,000/yr" },
  { slug: "vermont", name: "Vermont", country: "United States", countryCode: "US", continent: "North America", region: "VT", currency: "USD", currencySymbol: "$", nearby: ["new-hampshire", "boston", "connecticut"], eventCost: "$300–$900", mealPrepCost: "$170–$370/day", fullTimeCost: "$48,000–$92,000/yr" },
  { slug: "new-jersey", name: "New Jersey", country: "United States", countryCode: "US", continent: "North America", region: "NJ", currency: "USD", currencySymbol: "$", nearby: ["new-york", "philadelphia", "connecticut"], eventCost: "$350–$1,000", mealPrepCost: "$200–$420/day", fullTimeCost: "$58,000–$110,000/yr" },
  { slug: "philadelphia", name: "Philadelphia", country: "United States", countryCode: "US", continent: "North America", region: "PA", currency: "USD", currencySymbol: "$", nearby: ["new-york", "new-jersey", "baltimore", "washington-dc"], eventCost: "$350–$1,000", mealPrepCost: "$200–$420/day", fullTimeCost: "$58,000–$110,000/yr" },
  { slug: "pittsburgh", name: "Pittsburgh", country: "United States", countryCode: "US", continent: "North America", region: "PA", currency: "USD", currencySymbol: "$", nearby: ["philadelphia", "cleveland", "columbus"], eventCost: "$280–$800", mealPrepCost: "$160–$330/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "washington-dc", name: "Washington DC", country: "United States", countryCode: "US", continent: "North America", region: "DC", currency: "USD", currencySymbol: "$", nearby: ["baltimore", "philadelphia", "virginia-beach", "richmond"], eventCost: "$420–$1,300", mealPrepCost: "$260–$520/day", fullTimeCost: "$70,000–$130,000/yr" },
  { slug: "baltimore", name: "Baltimore", country: "United States", countryCode: "US", continent: "North America", region: "MD", currency: "USD", currencySymbol: "$", nearby: ["washington-dc", "philadelphia", "annapolis"], eventCost: "$320–$950", mealPrepCost: "$180–$380/day", fullTimeCost: "$52,000–$100,000/yr" },
  { slug: "richmond", name: "Richmond", country: "United States", countryCode: "US", continent: "North America", region: "VA", currency: "USD", currencySymbol: "$", nearby: ["washington-dc", "virginia-beach", "charlotte"], eventCost: "$300–$850", mealPrepCost: "$170–$360/day", fullTimeCost: "$50,000–$95,000/yr" },
  { slug: "virginia-beach", name: "Virginia Beach", country: "United States", countryCode: "US", continent: "North America", region: "VA", currency: "USD", currencySymbol: "$", nearby: ["outer-banks", "richmond", "washington-dc"], eventCost: "$300–$850", mealPrepCost: "$170–$360/day", fullTimeCost: "$50,000–$95,000/yr" },
  { slug: "westchester", name: "Westchester", country: "United States", countryCode: "US", continent: "North America", region: "NY", currency: "USD", currencySymbol: "$", nearby: ["new-york", "connecticut", "hamptons"], eventCost: "$420–$1,300", mealPrepCost: "$260–$520/day", fullTimeCost: "$68,000–$128,000/yr" },
  { slug: "new-orleans", name: "New Orleans", country: "United States", countryCode: "US", continent: "North America", region: "LA", currency: "USD", currencySymbol: "$", nearby: ["baton-rouge", "houston", "biloxi"], eventCost: "$350–$1,000", mealPrepCost: "$200–$420/day", fullTimeCost: "$52,000–$100,000/yr" },
  { slug: "indianapolis", name: "Indianapolis", country: "United States", countryCode: "US", continent: "North America", region: "IN", currency: "USD", currencySymbol: "$", nearby: ["chicago", "cincinnati", "louisville"], eventCost: "$280–$800", mealPrepCost: "$160–$330/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "minneapolis", name: "Minneapolis", country: "United States", countryCode: "US", continent: "North America", region: "MN", currency: "USD", currencySymbol: "$", nearby: ["milwaukee", "chicago", "kansas-city"], eventCost: "$320–$950", mealPrepCost: "$180–$380/day", fullTimeCost: "$52,000–$100,000/yr" },
  { slug: "milwaukee", name: "Milwaukee", country: "United States", countryCode: "US", continent: "North America", region: "WI", currency: "USD", currencySymbol: "$", nearby: ["chicago", "minneapolis", "madison"], eventCost: "$280–$800", mealPrepCost: "$160–$330/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "wisconsin-dells", name: "Wisconsin Dells", country: "United States", countryCode: "US", continent: "North America", region: "WI", currency: "USD", currencySymbol: "$", nearby: ["milwaukee", "chicago", "minneapolis"], eventCost: "$280–$800", mealPrepCost: "$160–$330/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "detroit", name: "Detroit", country: "United States", countryCode: "US", continent: "North America", region: "MI", currency: "USD", currencySymbol: "$", nearby: ["chicago", "toledo", "cleveland"], eventCost: "$280–$800", mealPrepCost: "$160–$330/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "grand-rapids", name: "Grand Rapids", country: "United States", countryCode: "US", continent: "North America", region: "MI", currency: "USD", currencySymbol: "$", nearby: ["detroit", "chicago", "traverse-city"], eventCost: "$270–$750", mealPrepCost: "$150–$320/day", fullTimeCost: "$43,000–$82,000/yr" },
  { slug: "traverse-city", name: "Traverse City", country: "United States", countryCode: "US", continent: "North America", region: "MI", currency: "USD", currencySymbol: "$", nearby: ["grand-rapids", "detroit", "milwaukee"], eventCost: "$300–$850", mealPrepCost: "$170–$360/day", fullTimeCost: "$48,000–$90,000/yr" },
  { slug: "columbus", name: "Columbus", country: "United States", countryCode: "US", continent: "North America", region: "OH", currency: "USD", currencySymbol: "$", nearby: ["cleveland", "cincinnati", "pittsburgh", "indianapolis"], eventCost: "$280–$800", mealPrepCost: "$160–$330/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "kansas-city", name: "Kansas City", country: "United States", countryCode: "US", continent: "North America", region: "MO", currency: "USD", currencySymbol: "$", nearby: ["st-louis", "omaha", "oklahoma-city", "wichita"], eventCost: "$280–$800", mealPrepCost: "$160–$330/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "st-louis", name: "St. Louis", country: "United States", countryCode: "US", continent: "North America", region: "MO", currency: "USD", currencySymbol: "$", nearby: ["kansas-city", "indianapolis", "chicago", "nashville"], eventCost: "$280–$800", mealPrepCost: "$160–$330/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "omaha", name: "Omaha", country: "United States", countryCode: "US", continent: "North America", region: "NE", currency: "USD", currencySymbol: "$", nearby: ["kansas-city", "lincoln", "minneapolis"], eventCost: "$260–$750", mealPrepCost: "$145–$300/day", fullTimeCost: "$42,000–$80,000/yr" },
  { slug: "lincoln", name: "Lincoln", country: "United States", countryCode: "US", continent: "North America", region: "NE", currency: "USD", currencySymbol: "$", nearby: ["omaha", "kansas-city"], eventCost: "$250–$700", mealPrepCost: "$140–$290/day", fullTimeCost: "$40,000–$78,000/yr" },
  { slug: "wichita", name: "Wichita", country: "United States", countryCode: "US", continent: "North America", region: "KS", currency: "USD", currencySymbol: "$", nearby: ["kansas-city", "oklahoma-city", "tulsa"], eventCost: "$250–$700", mealPrepCost: "$140–$290/day", fullTimeCost: "$40,000–$78,000/yr" },
  { slug: "oklahoma-city", name: "Oklahoma City", country: "United States", countryCode: "US", continent: "North America", region: "OK", currency: "USD", currencySymbol: "$", nearby: ["tulsa", "wichita", "dallas"], eventCost: "$260–$750", mealPrepCost: "$145–$300/day", fullTimeCost: "$42,000–$80,000/yr" },
  { slug: "tulsa", name: "Tulsa", country: "United States", countryCode: "US", continent: "North America", region: "OK", currency: "USD", currencySymbol: "$", nearby: ["oklahoma-city", "broken-bow", "dallas"], eventCost: "$260–$750", mealPrepCost: "$145–$300/day", fullTimeCost: "$42,000–$80,000/yr" },
  { slug: "broken-bow", name: "Broken Bow", country: "United States", countryCode: "US", continent: "North America", region: "OK", currency: "USD", currencySymbol: "$", nearby: ["tulsa", "oklahoma-city", "dallas"], eventCost: "$280–$800", mealPrepCost: "$160–$330/day", fullTimeCost: "$42,000–$80,000/yr" },
  { slug: "louisville", name: "Louisville", country: "United States", countryCode: "US", continent: "North America", region: "KY", currency: "USD", currencySymbol: "$", nearby: ["nashville", "indianapolis", "lexington", "cincinnati"], eventCost: "$270–$780", mealPrepCost: "$155–$320/day", fullTimeCost: "$44,000–$83,000/yr" },
  { slug: "lexington", name: "Lexington", country: "United States", countryCode: "US", continent: "North America", region: "KY", currency: "USD", currencySymbol: "$", nearby: ["louisville", "nashville", "knoxville"], eventCost: "$260–$750", mealPrepCost: "$145–$305/day", fullTimeCost: "$42,000–$80,000/yr" },
  { slug: "lake-tahoe", name: "Lake Tahoe", country: "United States", countryCode: "US", continent: "North America", region: "CA/NV", currency: "USD", currencySymbol: "$", nearby: ["san-francisco", "napa", "reno"], eventCost: "$450–$1,400", mealPrepCost: "$280–$560/day", fullTimeCost: "$65,000–$125,000/yr" },
  { slug: "lake-ozarks", name: "Lake of the Ozarks", country: "United States", countryCode: "US", continent: "North America", region: "MO", currency: "USD", currencySymbol: "$", nearby: ["st-louis", "kansas-city"], eventCost: "$280–$800", mealPrepCost: "$160–$330/day", fullTimeCost: "$45,000–$85,000/yr" },
  { slug: "bozeman", name: "Bozeman", country: "United States", countryCode: "US", continent: "North America", region: "MT", currency: "USD", currencySymbol: "$", nearby: ["jackson-hole", "billings"], eventCost: "$320–$950", mealPrepCost: "$180–$380/day", fullTimeCost: "$50,000–$95,000/yr" },
  { slug: "jackson-hole", name: "Jackson Hole", country: "United States", countryCode: "US", continent: "North America", region: "WY", currency: "USD", currencySymbol: "$", nearby: ["bozeman", "salt-lake-city", "vail"], eventCost: "$500–$1,600", mealPrepCost: "$320–$620/day", fullTimeCost: "$70,000–$135,000/yr" },
  { slug: "salt-lake-city", name: "Salt Lake City", country: "United States", countryCode: "US", continent: "North America", region: "UT", currency: "USD", currencySymbol: "$", nearby: ["park-city", "jackson-hole", "las-vegas"], eventCost: "$300–$900", mealPrepCost: "$170–$370/day", fullTimeCost: "$50,000–$95,000/yr" },
  { slug: "park-city", name: "Park City", country: "United States", countryCode: "US", continent: "North America", region: "UT", currency: "USD", currencySymbol: "$", nearby: ["salt-lake-city", "jackson-hole", "vail"], eventCost: "$450–$1,400", mealPrepCost: "$280–$560/day", fullTimeCost: "$65,000–$125,000/yr" },
  { slug: "albuquerque", name: "Albuquerque", country: "United States", countryCode: "US", continent: "North America", region: "NM", currency: "USD", currencySymbol: "$", nearby: ["santa-fe", "el-paso", "phoenix"], eventCost: "$260–$750", mealPrepCost: "$145–$300/day", fullTimeCost: "$42,000–$80,000/yr" },
  { slug: "santa-fe", name: "Santa Fe", country: "United States", countryCode: "US", continent: "North America", region: "NM", currency: "USD", currencySymbol: "$", nearby: ["albuquerque", "taos", "el-paso"], eventCost: "$320–$950", mealPrepCost: "$180–$380/day", fullTimeCost: "$50,000–$95,000/yr" },
  { slug: "honolulu", name: "Honolulu", country: "United States", countryCode: "US", continent: "North America", region: "HI", currency: "USD", currencySymbol: "$", nearby: ["maui", "kauai", "kona", "oahu"], eventCost: "$450–$1,400", mealPrepCost: "$280–$560/day", fullTimeCost: "$65,000–$125,000/yr" },
  { slug: "maui", name: "Maui", country: "United States", countryCode: "US", continent: "North America", region: "HI", currency: "USD", currencySymbol: "$", nearby: ["honolulu", "kauai", "kona", "oahu"], eventCost: "$500–$1,600", mealPrepCost: "$320–$620/day", fullTimeCost: "$70,000–$135,000/yr" },
  { slug: "kauai", name: "Kauai", country: "United States", countryCode: "US", continent: "North America", region: "HI", currency: "USD", currencySymbol: "$", nearby: ["maui", "honolulu", "oahu"], eventCost: "$450–$1,400", mealPrepCost: "$280–$560/day", fullTimeCost: "$65,000–$125,000/yr" },
  { slug: "kona", name: "Kona", country: "United States", countryCode: "US", continent: "North America", region: "HI", currency: "USD", currencySymbol: "$", nearby: ["honolulu", "maui", "oahu"], eventCost: "$420–$1,300", mealPrepCost: "$260–$520/day", fullTimeCost: "$62,000–$120,000/yr" },
  { slug: "oahu", name: "Oahu", country: "United States", countryCode: "US", continent: "North America", region: "HI", currency: "USD", currencySymbol: "$", nearby: ["honolulu", "maui", "kauai", "kona"], eventCost: "$450–$1,400", mealPrepCost: "$280–$560/day", fullTimeCost: "$65,000–$125,000/yr" },

  // ── CARIBBEAN / CENTRAL AMERICA ──────────────────────────────────
  { slug: "aruba", name: "Aruba", country: "Aruba", countryCode: "AW", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["curacao", "barbados", "turks-and-caicos"], eventCost: "$350–$1,000", mealPrepCost: "$200–$420/day", fullTimeCost: "$40,000–$80,000/yr" },
  { slug: "curacao", name: "Curacao", country: "Curacao", countryCode: "CW", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["aruba", "barbados", "turks-and-caicos"], eventCost: "$300–$900", mealPrepCost: "$170–$370/day", fullTimeCost: "$38,000–$75,000/yr" },
  { slug: "barbados", name: "Barbados", country: "Barbados", countryCode: "BB", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["aruba", "curacao", "turks-and-caicos", "st-thomas"], eventCost: "$380–$1,200", mealPrepCost: "$220–$460/day", fullTimeCost: "$42,000–$85,000/yr" },
  { slug: "turks-and-caicos", name: "Turks and Caicos", country: "Turks and Caicos", countryCode: "TC", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["bahamas", "aruba", "st-thomas", "barbados"], eventCost: "$500–$1,800", mealPrepCost: "$320–$650/day", fullTimeCost: "$55,000–$110,000/yr" },
  { slug: "exuma-bahamas", name: "Exuma, Bahamas", country: "Bahamas", countryCode: "BS", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["turks-and-caicos", "barbados", "miami"], eventCost: "$500–$1,800", mealPrepCost: "$320–$650/day", fullTimeCost: "$55,000–$110,000/yr" },
  { slug: "st-thomas", name: "St. Thomas", country: "US Virgin Islands", countryCode: "VI", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["barbados", "aruba", "turks-and-caicos"], eventCost: "$400–$1,300", mealPrepCost: "$250–$500/day", fullTimeCost: "$48,000–$95,000/yr" },
  { slug: "grand-cayman", name: "Grand Cayman", country: "Cayman Islands", countryCode: "KY", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["jamaica", "turks-and-caicos", "barbados"], eventCost: "$500–$1,600", mealPrepCost: "$320–$620/day", fullTimeCost: "$55,000–$110,000/yr" },
  { slug: "puerto-rico", name: "Puerto Rico", country: "Puerto Rico", countryCode: "PR", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["st-thomas", "barbados", "miami"], eventCost: "$320–$950", mealPrepCost: "$180–$380/day", fullTimeCost: "$42,000–$82,000/yr" },
  { slug: "tulum", name: "Tulum", country: "Mexico", countryCode: "MX", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["cancun", "isla-mujeres", "playa-del-carmen"], eventCost: "$300–$900", mealPrepCost: "$170–$370/day", fullTimeCost: "$25,000–$55,000/yr" },
  { slug: "cancun", name: "Cancun", country: "Mexico", countryCode: "MX", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["tulum", "isla-mujeres", "playa-del-carmen"], eventCost: "$280–$850", mealPrepCost: "$160–$350/day", fullTimeCost: "$22,000–$50,000/yr" },
  { slug: "isla-mujeres", name: "Isla Mujeres", country: "Mexico", countryCode: "MX", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["cancun", "tulum", "playa-del-carmen"], eventCost: "$280–$850", mealPrepCost: "$160–$340/day", fullTimeCost: "$22,000–$48,000/yr" },
  { slug: "cabo", name: "Cabo San Lucas", country: "Mexico", countryCode: "MX", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["cancun", "puerto-vallarta", "mazatlan"], eventCost: "$350–$1,100", mealPrepCost: "$200–$430/day", fullTimeCost: "$28,000–$62,000/yr" },
  { slug: "mexico-city", name: "Mexico City", country: "Mexico", countryCode: "MX", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["cancun", "guadalajara", "cabo"], eventCost: "$280–$850", mealPrepCost: "$160–$340/day", fullTimeCost: "$22,000–$50,000/yr" },
  { slug: "costa-rica", name: "Costa Rica", country: "Costa Rica", countryCode: "CR", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["tulum", "cancun", "el-salvador"], eventCost: "$280–$850", mealPrepCost: "$160–$350/day", fullTimeCost: "$22,000–$50,000/yr" },
  { slug: "tamarindo", name: "Tamarindo", country: "Costa Rica", countryCode: "CR", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["costa-rica", "quepos", "uvita"], eventCost: "$300–$900", mealPrepCost: "$170–$370/day", fullTimeCost: "$24,000–$55,000/yr" },
  { slug: "quepos", name: "Quepos", country: "Costa Rica", countryCode: "CR", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["tamarindo", "uvita", "costa-rica"], eventCost: "$280–$850", mealPrepCost: "$160–$340/day", fullTimeCost: "$22,000–$50,000/yr" },
  { slug: "uvita", name: "Uvita", country: "Costa Rica", countryCode: "CR", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["quepos", "tamarindo", "costa-rica"], eventCost: "$280–$850", mealPrepCost: "$160–$340/day", fullTimeCost: "$22,000–$50,000/yr" },
  { slug: "el-salvador", name: "El Salvador", country: "El Salvador", countryCode: "SV", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["costa-rica", "cancun", "tulum"], eventCost: "$200–$600", mealPrepCost: "$120–$280/day", fullTimeCost: "$18,000–$42,000/yr" },
  { slug: "punta-cana", name: "Punta Cana", country: "Dominican Republic", countryCode: "DO", continent: "North America", currency: "USD", currencySymbol: "$", nearby: ["turks-and-caicos", "barbados", "miami"], eventCost: "$300–$900", mealPrepCost: "$170–$370/day", fullTimeCost: "$25,000–$55,000/yr" },

  // ── CANADA ────────────────────────────────────────────────────────
  { slug: "toronto", name: "Toronto", country: "Canada", countryCode: "CA", continent: "North America", region: "ON", currency: "CAD", currencySymbol: "CA$", nearby: ["niagara", "hamilton", "ottawa", "muskoka"], eventCost: "CA$400–CA$1,200", mealPrepCost: "CA$250–CA$500/day", fullTimeCost: "CA$65,000–CA$120,000/yr" },
  { slug: "muskoka", name: "Muskoka", country: "Canada", countryCode: "CA", continent: "North America", region: "ON", currency: "CAD", currencySymbol: "CA$", nearby: ["toronto", "ottawa"], eventCost: "CA$420–CA$1,300", mealPrepCost: "CA$260–CA$520/day", fullTimeCost: "CA$65,000–CA$125,000/yr" },
  { slug: "ottawa", name: "Ottawa", country: "Canada", countryCode: "CA", continent: "North America", region: "ON", currency: "CAD", currencySymbol: "CA$", nearby: ["toronto", "montreal", "muskoka"], eventCost: "CA$350–CA$1,000", mealPrepCost: "CA$200–CA$420/day", fullTimeCost: "CA$58,000–CA$108,000/yr" },
  { slug: "montreal", name: "Montreal", country: "Canada", countryCode: "CA", continent: "North America", region: "QC", currency: "CAD", currencySymbol: "CA$", nearby: ["ottawa", "quebec-city", "toronto"], eventCost: "CA$350–CA$1,000", mealPrepCost: "CA$200–CA$420/day", fullTimeCost: "CA$55,000–CA$105,000/yr" },
  { slug: "quebec-city", name: "Quebec City", country: "Canada", countryCode: "CA", continent: "North America", region: "QC", currency: "CAD", currencySymbol: "CA$", nearby: ["montreal", "ottawa"], eventCost: "CA$320–CA$950", mealPrepCost: "CA$180–CA$380/day", fullTimeCost: "CA$50,000–CA$98,000/yr" },
  { slug: "vancouver", name: "Vancouver", country: "Canada", countryCode: "CA", continent: "North America", region: "BC", currency: "CAD", currencySymbol: "CA$", nearby: ["kelowna", "victoria", "whistler", "seattle"], eventCost: "CA$420–CA$1,300", mealPrepCost: "CA$260–CA$520/day", fullTimeCost: "CA$65,000–CA$125,000/yr" },
  { slug: "kelowna", name: "Kelowna", country: "Canada", countryCode: "CA", continent: "North America", region: "BC", currency: "CAD", currencySymbol: "CA$", nearby: ["vancouver", "victoria", "whistler"], eventCost: "CA$320–CA$950", mealPrepCost: "CA$180–CA$380/day", fullTimeCost: "CA$50,000–CA$98,000/yr" },
  { slug: "calgary", name: "Calgary", country: "Canada", countryCode: "CA", continent: "North America", region: "AB", currency: "CAD", currencySymbol: "CA$", nearby: ["edmonton", "banff", "vancouver"], eventCost: "CA$350–CA$1,000", mealPrepCost: "CA$200–CA$420/day", fullTimeCost: "CA$58,000–CA$110,000/yr" },
  { slug: "edmonton", name: "Edmonton", country: "Canada", countryCode: "CA", continent: "North America", region: "AB", currency: "CAD", currencySymbol: "CA$", nearby: ["calgary", "vancouver"], eventCost: "CA$320–CA$950", mealPrepCost: "CA$180–CA$380/day", fullTimeCost: "CA$52,000–CA$100,000/yr" },
  { slug: "winnipeg", name: "Winnipeg", country: "Canada", countryCode: "CA", continent: "North America", region: "MB", currency: "CAD", currencySymbol: "CA$", nearby: ["calgary", "edmonton", "toronto"], eventCost: "CA$280–CA$800", mealPrepCost: "CA$160–CA$330/day", fullTimeCost: "CA$45,000–CA$85,000/yr" },

  // ── UNITED KINGDOM ───────────────────────────────────────────────
  { slug: "london", name: "London", country: "United Kingdom", countryCode: "GB", continent: "Europe", currency: "GBP", currencySymbol: "£", nearby: ["cotswolds", "brighton", "oxford", "cambridge", "surrey"], eventCost: "£350–£1,200", mealPrepCost: "£200–£480/day", fullTimeCost: "£40,000–£85,000/yr" },
  { slug: "cotswolds", name: "Cotswolds", country: "United Kingdom", countryCode: "GB", continent: "Europe", currency: "GBP", currencySymbol: "£", nearby: ["london", "oxford", "bath", "cheltenham"], eventCost: "£300–£1,000", mealPrepCost: "£180–£420/day", fullTimeCost: "£38,000–£78,000/yr" },
  { slug: "edinburgh", name: "Edinburgh", country: "United Kingdom", countryCode: "GB", continent: "Europe", currency: "GBP", currencySymbol: "£", nearby: ["glasgow", "st-andrews", "dundee"], eventCost: "£300–£950", mealPrepCost: "£170–£400/day", fullTimeCost: "£35,000–£72,000/yr" },
  { slug: "manchester", name: "Manchester", country: "United Kingdom", countryCode: "GB", continent: "Europe", currency: "GBP", currencySymbol: "£", nearby: ["liverpool", "leeds", "london", "lake-district"], eventCost: "£280–£850", mealPrepCost: "£160–£370/day", fullTimeCost: "£32,000–$68,000/yr" },
  { slug: "lake-district", name: "Lake District", country: "United Kingdom", countryCode: "GB", continent: "Europe", currency: "GBP", currencySymbol: "£", nearby: ["manchester", "edinburgh", "yorkshire"], eventCost: "£280–£900", mealPrepCost: "£160–£380/day", fullTimeCost: "£32,000–$68,000/yr" },
  { slug: "norfolk", name: "Norfolk", country: "United Kingdom", countryCode: "GB", continent: "Europe", currency: "GBP", currencySymbol: "£", nearby: ["london", "cambridge", "suffolk"], eventCost: "£270–£850", mealPrepCost: "£155–£360/day", fullTimeCost: "£30,000–$65,000/yr" },
  { slug: "bath", name: "Bath", country: "United Kingdom", countryCode: "GB", continent: "Europe", currency: "GBP", currencySymbol: "£", nearby: ["cotswolds", "london", "bristol"], eventCost: "£280–£900", mealPrepCost: "£160–£380/day", fullTimeCost: "£32,000–$68,000/yr" },

  // ── EUROPE ────────────────────────────────────────────────────────
  { slug: "paris", name: "Paris", country: "France", countryCode: "FR", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["versailles", "champagne", "bruges"], eventCost: "€350–€1,200", mealPrepCost: "€200–€480/day", fullTimeCost: "€42,000–€85,000/yr" },
  { slug: "barcelona", name: "Barcelona", country: "Spain", countryCode: "ES", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["madrid", "ibiza", "tarragona"], eventCost: "€280–€950", mealPrepCost: "€160–€400/day", fullTimeCost: "€35,000–€70,000/yr" },
  { slug: "madrid", name: "Madrid", country: "Spain", countryCode: "ES", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["barcelona", "seville", "toledo"], eventCost: "€280–€950", mealPrepCost: "€160–€400/day", fullTimeCost: "€35,000–€70,000/yr" },
  { slug: "ibiza", name: "Ibiza", country: "Spain", countryCode: "ES", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["barcelona", "madrid", "marbella", "mallorca"], eventCost: "€450–€1,600", mealPrepCost: "€280–€580/day", fullTimeCost: "€45,000–€95,000/yr" },
  { slug: "marbella", name: "Marbella", country: "Spain", countryCode: "ES", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["ibiza", "seville", "malaga"], eventCost: "€380–€1,300", mealPrepCost: "€220–€500/day", fullTimeCost: "€40,000–€82,000/yr" },
  { slug: "rome", name: "Rome", country: "Italy", countryCode: "IT", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["florence", "naples", "tuscany", "milan"], eventCost: "€280–€950", mealPrepCost: "€160–€400/day", fullTimeCost: "€32,000–€70,000/yr" },
  { slug: "florence", name: "Florence", country: "Italy", countryCode: "IT", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["tuscany", "rome", "siena", "milan"], eventCost: "€280–€950", mealPrepCost: "€160–€400/day", fullTimeCost: "€30,000–€68,000/yr" },
  { slug: "tuscany", name: "Tuscany", country: "Italy", countryCode: "IT", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["florence", "rome", "siena", "cinque-terre"], eventCost: "€320–€1,100", mealPrepCost: "€180–€440/day", fullTimeCost: "€32,000–€72,000/yr" },
  { slug: "milan", name: "Milan", country: "Italy", countryCode: "IT", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["florence", "rome", "lake-como", "venice"], eventCost: "€300–€1,000", mealPrepCost: "€170–€420/day", fullTimeCost: "€35,000–€75,000/yr" },
  { slug: "venice", name: "Venice", country: "Italy", countryCode: "IT", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["milan", "florence", "rome", "lake-como"], eventCost: "€350–€1,200", mealPrepCost: "€200–€480/day", fullTimeCost: "€35,000–€75,000/yr" },
  { slug: "amalfi", name: "Amalfi Coast", country: "Italy", countryCode: "IT", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["rome", "naples", "sicily"], eventCost: "€350–€1,300", mealPrepCost: "€200–€500/day", fullTimeCost: "€35,000–€75,000/yr" },
  { slug: "mykonos", name: "Mykonos", country: "Greece", countryCode: "GR", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["santorini", "athens", "zakynthos", "corfu"], eventCost: "€400–€1,500", mealPrepCost: "€250–€550/day", fullTimeCost: "€35,000–€80,000/yr" },
  { slug: "santorini", name: "Santorini", country: "Greece", countryCode: "GR", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["mykonos", "athens", "crete"], eventCost: "€400–€1,500", mealPrepCost: "€250–€550/day", fullTimeCost: "€35,000–€80,000/yr" },
  { slug: "corfu", name: "Corfu", country: "Greece", countryCode: "GR", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["mykonos", "santorini", "zakynthos", "athens"], eventCost: "€320–€1,100", mealPrepCost: "€180–€440/day", fullTimeCost: "€30,000–€70,000/yr" },
  { slug: "zakynthos", name: "Zakynthos", country: "Greece", countryCode: "GR", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["corfu", "mykonos", "santorini"], eventCost: "€300–€1,000", mealPrepCost: "€170–€420/day", fullTimeCost: "€28,000–€65,000/yr" },
  { slug: "athens", name: "Athens", country: "Greece", countryCode: "GR", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["mykonos", "santorini", "corfu", "thessaloniki"], eventCost: "€280–€950", mealPrepCost: "£160–€400/day", fullTimeCost: "€28,000–€62,000/yr" },
  { slug: "amsterdam", name: "Amsterdam", country: "Netherlands", countryCode: "NL", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["brussels", "berlin", "paris", "london"], eventCost: "€320–€1,100", mealPrepCost: "€180–€440/day", fullTimeCost: "€40,000–€80,000/yr" },
  { slug: "berlin", name: "Berlin", country: "Germany", countryCode: "DE", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["amsterdam", "prague", "vienna", "munich"], eventCost: "€300–€1,000", mealPrepCost: "€170–€420/day", fullTimeCost: "€38,000–€78,000/yr" },
  { slug: "munich", name: "Munich", country: "Germany", countryCode: "DE", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["berlin", "vienna", "zurich", "salzburg"], eventCost: "€320–€1,100", mealPrepCost: "€180–€440/day", fullTimeCost: "€40,000–€82,000/yr" },
  { slug: "vienna", name: "Vienna", country: "Austria", countryCode: "AT", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["munich", "prague", "budapest", "salzburg"], eventCost: "€320–€1,100", mealPrepCost: "€180–€440/day", fullTimeCost: "€38,000–€80,000/yr" },
  { slug: "prague", name: "Prague", country: "Czech Republic", countryCode: "CZ", continent: "Europe", currency: "CZK", currencySymbol: "Kč", nearby: ["vienna", "berlin", "budapest", "krakow"], eventCost: "€250–€800", mealPrepCost: "€140–€320/day", fullTimeCost: "€28,000–€58,000/yr" },
  { slug: "budapest", name: "Budapest", country: "Hungary", countryCode: "HU", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["prague", "vienna", "krakow", "bucharest"], eventCost: "€220–€750", mealPrepCost: "€130–€300/day", fullTimeCost: "€25,000–€55,000/yr" },
  { slug: "lisbon", name: "Lisbon", country: "Portugal", countryCode: "PT", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["porto", "seville", "madrid", "algarve"], eventCost: "€280–€950", mealPrepCost: "€160–€400/day", fullTimeCost: "€30,000–€65,000/yr" },
  { slug: "porto", name: "Porto", country: "Portugal", countryCode: "PT", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["lisbon", "algarve", "madrid"], eventCost: "€260–$900", mealPrepCost: "€150–€380/day", fullTimeCost: "€28,000–€62,000/yr" },
  { slug: "zurich", name: "Zurich", country: "Switzerland", countryCode: "CH", continent: "Europe", currency: "CHF", currencySymbol: "CHF", nearby: ["zermatt", "geneva", "munich", "milan"], eventCost: "CHF 500–CHF 1,800", mealPrepCost: "CHF 300–CHF 650/day", fullTimeCost: "CHF 70,000–CHF 140,000/yr" },
  { slug: "zermatt", name: "Zermatt", country: "Switzerland", countryCode: "CH", continent: "Europe", currency: "CHF", currencySymbol: "CHF", nearby: ["zurich", "geneva", "milan"], eventCost: "CHF 600–CHF 2,200", mealPrepCost: "CHF 380–CHF 750/day", fullTimeCost: "CHF 80,000–CHF 160,000/yr" },
  { slug: "dubrovnik", name: "Dubrovnik", country: "Croatia", countryCode: "HR", continent: "Europe", currency: "EUR", currencySymbol: "€", nearby: ["split", "kotor", "hvar"], eventCost: "€300–€1,000", mealPrepCost: "€170–€400/day", fullTimeCost: "€28,000–€62,000/yr" },
  { slug: "oslo", name: "Oslo", country: "Norway", countryCode: "NO", continent: "Europe", currency: "NOK", currencySymbol: "kr", nearby: ["stockholm", "copenhagen", "bergen"], eventCost: "kr 3,500–kr 12,000", mealPrepCost: "kr 2,000–kr 5,000/day", fullTimeCost: "kr 500,000–kr 900,000/yr" },

  // ── MIDDLE EAST ───────────────────────────────────────────────────
  { slug: "dubai", name: "Dubai", country: "United Arab Emirates", countryCode: "AE", continent: "Middle East", currency: "AED", currencySymbol: "AED", nearby: ["abu-dhabi", "doha", "riyadh"], eventCost: "AED 1,500–AED 5,000", mealPrepCost: "AED 900–AED 2,000/day", fullTimeCost: "AED 180,000–AED 380,000/yr" },
  { slug: "abu-dhabi", name: "Abu Dhabi", country: "United Arab Emirates", countryCode: "AE", continent: "Middle East", currency: "AED", currencySymbol: "AED", nearby: ["dubai", "doha"], eventCost: "AED 1,400–AED 4,800", mealPrepCost: "AED 850–AED 1,900/day", fullTimeCost: "AED 170,000–AED 360,000/yr" },
  { slug: "doha", name: "Doha", country: "Qatar", countryCode: "QA", continent: "Middle East", currency: "QAR", currencySymbol: "QAR", nearby: ["dubai", "abu-dhabi", "riyadh"], eventCost: "QAR 2,000–QAR 6,500", mealPrepCost: "QAR 1,200–QAR 2,600/day", fullTimeCost: "QAR 180,000–QAR 360,000/yr" },

  // ── ASIA ─────────────────────────────────────────────────────────
  { slug: "bali", name: "Bali", country: "Indonesia", countryCode: "ID", continent: "Asia", currency: "USD", currencySymbol: "$", nearby: ["ubud", "uluwatu", "seminyak", "lombok"], eventCost: "$150–$500", mealPrepCost: "$80–$200/day", fullTimeCost: "$15,000–$35,000/yr" },
  { slug: "ubud", name: "Ubud", country: "Indonesia", countryCode: "ID", continent: "Asia", currency: "USD", currencySymbol: "$", nearby: ["bali", "uluwatu", "seminyak"], eventCost: "$150–$500", mealPrepCost: "$80–$200/day", fullTimeCost: "$15,000–$35,000/yr" },
  { slug: "uluwatu", name: "Uluwatu", country: "Indonesia", countryCode: "ID", continent: "Asia", currency: "USD", currencySymbol: "$", nearby: ["bali", "ubud", "seminyak"], eventCost: "$180–$600", mealPrepCost: "$100–$250/day", fullTimeCost: "$18,000–$40,000/yr" },
  { slug: "koh-samui", name: "Koh Samui", country: "Thailand", countryCode: "TH", continent: "Asia", currency: "THB", currencySymbol: "฿", nearby: ["phuket", "chiang-mai", "bangkok"], eventCost: "$200–$700", mealPrepCost: "$120–$280/day", fullTimeCost: "$18,000–$42,000/yr" },
  { slug: "phuket", name: "Phuket", country: "Thailand", countryCode: "TH", continent: "Asia", currency: "THB", currencySymbol: "฿", nearby: ["koh-samui", "chiang-mai", "bangkok"], eventCost: "$200–$700", mealPrepCost: "$120–$280/day", fullTimeCost: "$18,000–$42,000/yr" },
  { slug: "singapore", name: "Singapore", country: "Singapore", countryCode: "SG", continent: "Asia", currency: "SGD", currencySymbol: "S$", nearby: ["kuala-lumpur", "bali", "hong-kong"], eventCost: "S$500–S$1,800", mealPrepCost: "S$300–S$650/day", fullTimeCost: "S$70,000–S$140,000/yr" },
  { slug: "hong-kong", name: "Hong Kong", country: "Hong Kong", countryCode: "HK", continent: "Asia", currency: "HKD", currencySymbol: "HK$", nearby: ["singapore", "macau", "shanghai"], eventCost: "HK$3,000–HK$10,000", mealPrepCost: "HK$1,800–HK$4,200/day", fullTimeCost: "HK$450,000–HK$900,000/yr" },
  { slug: "tokyo", name: "Tokyo", country: "Japan", countryCode: "JP", continent: "Asia", currency: "JPY", currencySymbol: "¥", nearby: ["osaka", "kyoto", "yokohama"], eventCost: "¥60,000–¥200,000", mealPrepCost: "¥35,000–¥80,000/day", fullTimeCost: "¥6,000,000–¥12,000,000/yr" },
  { slug: "maldives", name: "Maldives", country: "Maldives", countryCode: "MV", continent: "Asia", currency: "USD", currencySymbol: "$", nearby: ["dubai", "singapore", "bali"], eventCost: "$500–$2,000", mealPrepCost: "$350–$750/day", fullTimeCost: "$45,000–$95,000/yr" },

  // ── AUSTRALIA / OCEANIA ───────────────────────────────────────────
  { slug: "sydney", name: "Sydney", country: "Australia", countryCode: "AU", continent: "Oceania", currency: "AUD", currencySymbol: "A$", nearby: ["hunter-valley", "blue-mountains", "canberra"], eventCost: "A$500–A$1,600", mealPrepCost: "A$300–A$620/day", fullTimeCost: "A$70,000–A$130,000/yr" },
  { slug: "melbourne", name: "Melbourne", country: "Australia", countryCode: "AU", continent: "Oceania", currency: "AUD", currencySymbol: "A$", nearby: ["great-ocean-road", "yarra-valley", "sydne"], eventCost: "A$480–A$1,500", mealPrepCost: "A$280–A$600/day", fullTimeCost: "A$68,000–A$125,000/yr" },
  { slug: "brisbane", name: "Brisbane", country: "Australia", countryCode: "AU", continent: "Oceania", currency: "AUD", currencySymbol: "A$", nearby: ["gold-coast", "noosa", "sunshine-coast"], eventCost: "A$420–A$1,300", mealPrepCost: "A$260–A$520/day", fullTimeCost: "A$60,000–A$115,000/yr" },
  { slug: "gold-coast", name: "Gold Coast", country: "Australia", countryCode: "AU", continent: "Oceania", currency: "AUD", currencySymbol: "A$", nearby: ["brisbane", "noosa", "byron-bay"], eventCost: "A$400–A$1,200", mealPrepCost: "A$240–A$480/day", fullTimeCost: "A$58,000–A$110,000/yr" },
  { slug: "noosa", name: "Noosa", country: "Australia", countryCode: "AU", continent: "Oceania", currency: "AUD", currencySymbol: "A$", nearby: ["brisbane", "gold-coast", "sunshine-coast"], eventCost: "A$400–A$1,300", mealPrepCost: "A$240–A$500/day", fullTimeCost: "A$58,000–A$112,000/yr" },
  { slug: "queenstown", name: "Queenstown", country: "New Zealand", countryCode: "NZ", continent: "Oceania", currency: "NZD", currencySymbol: "NZ$", nearby: ["christchurch", "dunedin"], eventCost: "NZ$480–NZ$1,600", mealPrepCost: "NZ$280–NZ$580/day", fullTimeCost: "NZ$65,000–NZ$125,000/yr" },

  // ── AFRICA ────────────────────────────────────────────────────────
  { slug: "cape-town", name: "Cape Town", country: "South Africa", countryCode: "ZA", continent: "Africa", currency: "ZAR", currencySymbol: "R", nearby: ["johannesburg", "durban", "stellenbosch"], eventCost: "R 4,500–R 15,000", mealPrepCost: "R 2,500–R 6,000/day", fullTimeCost: "R 300,000–R 650,000/yr" },
  { slug: "zanzibar", name: "Zanzibar", country: "Tanzania", countryCode: "TZ", continent: "Africa", currency: "USD", currencySymbol: "$", nearby: ["mombasa", "nairobi", "seychelles"], eventCost: "$200–$700", mealPrepCost: "$120–$300/day", fullTimeCost: "$18,000–$45,000/yr" },
  { slug: "marrakech", name: "Marrakech", country: "Morocco", countryCode: "MA", continent: "Africa", currency: "MAD", currencySymbol: "MAD", nearby: ["casablanca", "fez", "essaouira"], eventCost: "$200–$750", mealPrepCost: "$120–$300/day", fullTimeCost: "$18,000–$42,000/yr" },

  // ── SOUTH AMERICA ─────────────────────────────────────────────────
  { slug: "rio-de-janeiro", name: "Rio de Janeiro", country: "Brazil", countryCode: "BR", continent: "South America", currency: "BRL", currencySymbol: "R$", nearby: ["sao-paulo", "buzios", "petropolis"], eventCost: "R$ 1,200–R$ 4,500", mealPrepCost: "R$ 700–R$ 2,200/day", fullTimeCost: "R$ 80,000–R$ 180,000/yr" },
  { slug: "buenos-aires", name: "Buenos Aires", country: "Argentina", countryCode: "AR", continent: "South America", currency: "USD", currencySymbol: "$", nearby: ["montevideo", "punta-del-este"], eventCost: "$150–$500", mealPrepCost: "$90–$220/day", fullTimeCost: "$15,000–$38,000/yr" },
];

export function getLocationBySlug(slug: string): Location | undefined {
  return LOCATIONS.find((l) => l.slug === slug);
}

export function getAllLocationSlugs(): string[] {
  return LOCATIONS.map((l) => l.slug);
}

export function getNearbyLocations(slug: string, limit = 6): Location[] {
  const loc = getLocationBySlug(slug);
  if (!loc) return [];
  return loc.nearby
    .map((s) => getLocationBySlug(s))
    .filter((l): l is Location => l !== undefined)
    .slice(0, limit);
}

export function getLocationsByContinent(continent: Location["continent"]): Location[] {
  return LOCATIONS.filter((l) => l.continent === continent);
}

export function getPopularLocations(): Location[] {
  const popular = [
    "london", "new-york", "los-angeles", "miami", "dubai", "bali",
    "paris", "sydney", "tokyo", "ibiza", "tuscany", "mykonos",
    "las-vegas", "austin", "nashville", "boston", "cancun", "tulum",
    "barcelona", "amsterdam", "toronto", "san-francisco", "honolulu", "aspen",
  ];
  return popular.map((s) => getLocationBySlug(s)).filter((l): l is Location => l !== undefined);
}

export const CONTINENTS: Location["continent"][] = [
  "North America", "Europe", "Asia", "Oceania", "South America", "Africa", "Middle East",
];
